version: "3.9"

volumes:
  shared:

services:
  mysql:
    image: mysql:8
    command: >
      --default_authentication_plugin=mysql_native_password
      --secure-file-priv=""
    restart: unless-stopped
    ports:
      - "1337:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: taskich
      MYSQL_USER: "123"
      MYSQL_PASSWORD: verysecurepasswordgagaga
    volumes:
      - shared:/var/lib/mysql-files
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -prootpass -h localhost || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20

  php:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    working_dir: /app
    command: php -S 0.0.0.0:8080 -t /app/public
    ports:
      - "8080:8080"
    volumes:
      - shared:/app/public/uploads
