version: "3.9"

services:
  mysql:
    image: mysql:8
    command: >
      --default-authentication-plugin=mysql_native_password
      --secure-file-priv="" 
    container_name: vuln-mysql
    restart: unless-stopped
    ports:
      - "1337:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: taskich
      MYSQL_USER: "123"
      MYSQL_PASSWORD: verysecurepasswordgagaga         
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  php:
    build: .  
    depends_on:
      mysql:
        condition: service_healthy
    working_dir: /app
    command: php -S 0.0.0.0:8080 -t /app/public
    ports:
      - "8080:8080"
