services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: verysecurepasswordgagaga
      POSTGRES_DB: taskich
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html

volumes:
  postgres:
