services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: verysecurepasswordgagaga
      POSTGRES_DB: taskich
    volumes:
      - shared:/var/lib/postgresql/data/files

  php:
    build: .
    depends_on:
      - db
    volumes:
      - shared:/app/public/uploads

volumes:
  shared:
